"""MFBlock content type schema."""

from plone.autoform import directives
from plone.dexterity.content import Container
from plone.namedfile.field import NamedBlobFile
from plone.supermodel import model
from zope import schema
from zope.interface import implementer


class IMFBlock(model.Schema):
    """Schema for Module Federation Block."""

    title = schema.TextLine(
        title=u"Block Title",
        description=u"Human-readable name (e.g. 'Spacer')",
        required=True,
    )

    remote_name = schema.TextLine(
        title=u"Remote Name",
        description=u"Webpack container name (e.g. 'voltoSpacerBlock'). Must match the 'name' in webpack.config.js of the block.",
        required=True,
    )

    remote_module = schema.TextLine(
        title=u"Remote Module",
        description=u"Exposed module path (e.g. './SpacerBlock')",
        required=True,
        default=u"./block",
    )

    block_id = schema.TextLine(
        title=u"Block ID",
        description=u"Unique block ID for Volto (e.g. 'spacer'). This is the key used in blocksConfig.",
        required=True,
    )

    block_group = schema.Choice(
        title=u"Block Group",
        description=u"Group in the block chooser",
        values=[u"bricks", u"common", u"text", u"media", u"mostUsed"],
        default=u"bricks",
        required=True,
    )

    version = schema.TextLine(
        title=u"Version",
        description=u"Semantic version of this block (e.g. '1.0.0')",
        required=False,
        default=u"1.0.0",
    )

    bundle = NamedBlobFile(
        title=u"Bundle (.tar.gz)",
        description=u"Compiled block bundle. Upload the .tar.gz generated by 'npm run build'.",
        required=True,
    )

    active = schema.Bool(
        title=u"Active",
        description=u"Enable or disable this block in Volto",
        default=True,
        required=False,
    )


@implementer(IMFBlock)
class MFBlock(Container):
    """A Module Federation Block content type."""
    pass
